### ISSUE TITLE
Examples of solutions?

### ISSUE THREAD

**Issue by srph** [rstacruz/frontend-exercises#1]
Maybe a list of repositories that solved a certain exercise? By the way, I made mine, but I am not sure if it's functioning as described.

https://github.com/srph/frontend-exercises-order-form-react

**Comment by rstacruz** [comment]
good work! you won't see Project Euler or Koans have any solutions, so... leaving that as an exercise to the reader (like you've done) ;)

**Comment by srph** [comment]
Ooh, right! Thanks.
